// <auto-generated />
using System;
using AccesoDatos;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AccesoDatos.Migraciones
{
    [DbContext(typeof(CoachDbContext))]
    [Migration("20261003010044_TrabajosSoloParciales")]
    partial class TrabajosSoloParciales
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Entidades.Anotacion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("AtletaId")
                        .HasColumnType("integer");

                    b.Property<string>("AudioContentType")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int?>("AudioDuracionSegundos")
                        .HasColumnType("integer");

                    b.Property<string>("AudioRuta")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<long?>("AudioTamanioBytes")
                        .HasColumnType("bigint");

                    b.Property<double?>("ConfianzaPromedio")
                        .HasColumnType("double precision");

                    b.Property<int?>("EntrenamientoId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Idioma")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("ModeloTranscripcion")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Origen")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("ProveedorTranscripcion")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<bool>("RequiereRevision")
                        .HasColumnType("boolean");

                    b.Property<string>("Texto")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Titulo")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("TranscripcionOriginal")
                        .HasColumnType("text");

                    b.Property<int?>("UsuarioId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AtletaId");

                    b.HasIndex("EntrenamientoId");

                    b.HasIndex("FechaCreacion");

                    b.HasIndex("Origen");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Anotaciones", (string)null);
                });

            modelBuilder.Entity("Entidades.Atleta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Club")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("Dni")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Email")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<DateTime>("FechaAlta")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly>("FechaNacimiento")
                        .HasColumnType("date");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Telefono")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.HasKey("Id");

                    b.HasIndex("Dni")
                        .IsUnique();

                    b.ToTable("Atletas", (string)null);
                });

            modelBuilder.Entity("Entidades.Entrenamiento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Club")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<DateOnly>("Fecha")
                        .HasColumnType("date");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Sesion")
                        .HasColumnType("integer");

                    b.Property<string>("Turno")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.HasIndex("Fecha", "Turno", "Sesion")
                        .IsUnique();

                    b.ToTable("Entrenamientos", (string)null);
                });

            modelBuilder.Entity("Entidades.EntrenamientoAtleta", b =>
                {
                    b.Property<int>("EntrenamientoId")
                        .HasColumnType("integer");

                    b.Property<int>("AtletaId")
                        .HasColumnType("integer");

                    b.Property<bool?>("Asistio")
                        .HasColumnType("boolean");

                    b.HasKey("EntrenamientoId", "AtletaId");

                    b.HasIndex("AtletaId");

                    b.ToTable("EntrenamientoAtletas", (string)null);
                });

            modelBuilder.Entity("Entidades.Trabajo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AtletaId")
                        .HasColumnType("integer");

                    b.Property<int>("EntrenamientoId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<TimeOnly?>("HoraInicio")
                        .HasColumnType("time without time zone");

                    b.Property<string>("Observaciones")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.HasKey("Id");

                    b.HasIndex("EntrenamientoId", "AtletaId");

                    b.ToTable("Trabajos", (string)null);
                });

            modelBuilder.Entity("Entidades.TrabajoParcial", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("DistanciaMetros")
                        .HasColumnType("integer");

                    b.Property<int>("Orden")
                        .HasColumnType("integer");

                    b.Property<TimeSpan>("Tiempo")
                        .HasColumnType("interval");

                    b.Property<int>("TrabajoId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("TrabajoId", "Orden");

                    b.ToTable("TrabajoParciales", (string)null);
                });

            modelBuilder.Entity("Entidades.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("NombreUsuario")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Rol")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<DateTime?>("UltimoAcceso")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("NombreUsuario")
                        .IsUnique();

                    b.ToTable("Usuarios", (string)null);
                });

            modelBuilder.Entity("Entidades.Anotacion", b =>
                {
                    b.HasOne("Entidades.Atleta", "Atleta")
                        .WithMany("Anotaciones")
                        .HasForeignKey("AtletaId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Entidades.Entrenamiento", "Entrenamiento")
                        .WithMany("Anotaciones")
                        .HasForeignKey("EntrenamientoId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Entidades.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Atleta");

                    b.Navigation("Entrenamiento");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Entidades.EntrenamientoAtleta", b =>
                {
                    b.HasOne("Entidades.Atleta", "Atleta")
                        .WithMany("Entrenamientos")
                        .HasForeignKey("AtletaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Entidades.Entrenamiento", "Entrenamiento")
                        .WithMany("Atletas")
                        .HasForeignKey("EntrenamientoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Atleta");

                    b.Navigation("Entrenamiento");
                });

            modelBuilder.Entity("Entidades.Trabajo", b =>
                {
                    b.HasOne("Entidades.EntrenamientoAtleta", "EntrenamientoAtleta")
                        .WithMany("Trabajos")
                        .HasForeignKey("EntrenamientoId", "AtletaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EntrenamientoAtleta");
                });

            modelBuilder.Entity("Entidades.TrabajoParcial", b =>
                {
                    b.HasOne("Entidades.Trabajo", "Trabajo")
                        .WithMany("Parciales")
                        .HasForeignKey("TrabajoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Trabajo");
                });

            modelBuilder.Entity("Entidades.Atleta", b =>
                {
                    b.Navigation("Anotaciones");

                    b.Navigation("Entrenamientos");
                });

            modelBuilder.Entity("Entidades.Entrenamiento", b =>
                {
                    b.Navigation("Anotaciones");

                    b.Navigation("Atletas");
                });

            modelBuilder.Entity("Entidades.EntrenamientoAtleta", b =>
                {
                    b.Navigation("Trabajos");
                });

            modelBuilder.Entity("Entidades.Trabajo", b =>
                {
                    b.Navigation("Parciales");
                });
#pragma warning restore 612, 618
        }
    }
}
